const projects=[
{id:'8157',title:'BUILDING 8157',kicker:'PROJECT / 01',meta:'BIM MODEL • POINT CLOUD + BIM • PROJECT VIDEO',facts:['Existing Building','Revit BIM','Plans + Sections + Elevations'],cover:'assets/building-8157/model.png',cloud:'assets/building-8157/pointcloud-bim.png',video:'assets/building-8157/project.mp4',desc:'A building documentation package combining a 3D BIM model, point-cloud overlay and a model walkthrough. The supplied package also includes floor plans, sections, elevations and a half-cut model view.',details:[['Model view','assets/building-8157/model.png'],['Point Cloud + BIM','assets/building-8157/pointcloud-bim.png'],['Half-cut / detail','assets/building-8157/detail.png'],['Elevations','assets/building-8157/elevations.png'],['Floor plan 01','assets/building-8157/plan-1.png'],['Floor plan 02','assets/building-8157/plan-2.png'],['Floor plan 03','assets/building-8157/plan-3.png'],['Floor plan 04','assets/building-8157/plan-4.png'],['Section 01','assets/building-8157/section-1.png'],['Section 02','assets/building-8157/section-2.png']]},
{id:'jc',title:'JC BUJUMBURA',kicker:'PROJECT / 02',meta:'BIM MODEL • INDUSTRIAL / PLANT VISUALS • PROJECT VIDEO',facts:['Industrial / Plant Visuals','Equipment + Piping','Model Presentation'],cover:'assets/jc-bujumbura/model-2.png',cloud:'assets/jc-bujumbura/project-board.jpg',video:'assets/jc-bujumbura/project-web.mp4',desc:'An industrial project presentation showing equipment, piping and model views. The supplied material includes multiple model screenshots, a project board and a video walkthrough.',details:[['Primary model','assets/jc-bujumbura/model-2.png'],['Model view','assets/jc-bujumbura/model-1.png'],['Project board','assets/jc-bujumbura/project-board.jpg'],['Project overview','assets/jc-bujumbura/info-board.jpg'],['Presentation graphic','assets/jc-bujumbura/brand-board.png']]},
{id:'rdch',title:'RDCH RIAD',kicker:'PROJECT / 03',meta:'ARCHITECTURAL BIM • CUT VIEW • PROJECT VIDEO',facts:['Architectural Model','Cut / Section View','3D Walkthrough'],cover:'assets/rdch-riad/model.png',cloud:'assets/rdch-riad/cut-view.png',video:'assets/rdch-riad/project.mp4',desc:'An architectural building model presented through a 3D view, cut view and walkthrough video. The supplied files are used as the project visual set without inventing project specifications.',details:[['3D architectural model','assets/rdch-riad/model.png'],['Cut view','assets/rdch-riad/cut-view.png']]}
];
const grid=document.getElementById('projectGrid');
function card(p){return `<article class="project reveal" data-id="${p.id}"><div class="project-top"><div><div class="project-tag">${p.kicker}</div><h3 class="project-title">${p.title}</h3><div class="project-meta">${p.meta}</div></div><div class="project-meta">CLICK TO EXPLORE ↗</div></div><div class="project-media"><div class="media"><span class="media-label">01 / 3D BIM MODEL</span><img src="${p.cover}" alt="${p.title} BIM model"></div><div class="media"><span class="media-label">02 / ${p.id==='8157'?'POINT CLOUD + BIM':'PROJECT VISUAL'}</span><img src="${p.cloud}" alt="${p.title} project visual"></div><div class="media"><span class="media-label">03 / PROJECT VIDEO</span><video src="${p.video}" autoplay muted loop playsinline preload="metadata"></video></div></div><div class="project-bottom"><span>${p.facts.join('  /  ')}</span><span class="view">View project ↗</span></div></article>`}
grid.innerHTML=projects.map(card).join('');
const modal=document.getElementById('modal'), content=document.getElementById('modalContent');
function openProject(id){const p=projects.find(x=>x.id===id); if(!p)return; content.innerHTML=`<div class="modal-kicker">${p.kicker} / ${p.meta}</div><h2 class="modal-title">${p.title}</h2><div class="modal-facts">${p.facts.map(x=>`<span>${x}</span>`).join('')}</div><p class="modal-desc">${p.desc}</p><div class="detail-grid"><figure><img src="${p.cover}" alt="${p.title} model"><figcaption class="modal-caption">Primary model view</figcaption></figure><figure><img src="${p.cloud}" alt="${p.title} secondary project view"><figcaption class="modal-caption">${p.id==='8157'?'Point cloud + BIM':'Secondary project visual'}</figcaption></figure><figure class="detail-wide"><video src="${p.video}" autoplay muted loop controls playsinline></video><figcaption class="modal-caption">Project walkthrough / supplied video</figcaption></figure>${p.details.map(d=>`<figure><img src="${d[1]}" alt="${d[0]}"><figcaption class="modal-caption">${d[0]}</figcaption></figure>`).join('')}</div><div class="modal-note">The project detail view is intentionally visual-first. More project information can be added when the final project scope, LOD, area and deliverables are confirmed.</div>`; modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
grid.addEventListener('click',e=>{const el=e.target.closest('.project');if(el)openProject(el.dataset.id)});document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeModal));function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));
